#!/usr/bin/env Rscript
# Regenerate every .Renviron in the project from config/config.txt.
#
# Why this exists: shiny-server starts R and loads shiny *before* it reaches
# global.R, and on the HPC shiny itself lives inside lib/. So R_LIBS has to come
# from .Renviron, which R reads at startup. To keep config.txt the only place a
# path is written by hand, .Renviron is generated from it rather than edited.
#
# Targets: the project root (the unified app) and every legacy app folder that
# already has one. Run after changing `lib` in config.txt, and when deploying.

args <- commandArgs(FALSE)
here <- dirname(sub("^--file=", "", grep("^--file=", args, value = TRUE)[1]))
source(file.path(here, "..", "R", "config.R"))

lib <- os_path("lib")

targets <- unique(c(
  file.path(os_root(), ".Renviron"),
  Sys.glob(file.path(os_root(), "*", ".Renviron"))
))

body <- c(
  "# Generated by tools/sync-renviron.R from config/config.txt -- do not edit.",
  paste0("# Source: ", os_config_file()),
  paste0("R_LIBS=", lib),
  paste0("R_LIBS_USER=", lib)
)

for (t in targets) writeLines(body, t)

cat("R_LIBS=", lib, "\n", sep = "")
cat("wrote ", length(targets), " file(s):\n  ", paste(targets, collapse = "\n  "), "\n", sep = "")
if (!dir.exists(lib)) cat("note: that directory does not exist on this machine.\n")
